import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'src/components/atoms/Image'
import Footer from 'src/components/organisms/Footer'

import ChevronLeftIcon from '@heroicons/react/outline/ChevronLeftIcon'
import ChevronRightIcon from '@heroicons/react/outline/ChevronRightIcon'
import VideoPlayer from 'src/components/organisms/VideoPlayer'
import Navbar from 'src/components/organisms/Navbar'
import BannerItems from 'src/components/templates/BannerItems'
import Link from 'next/link'
import { useState } from 'react'

import { NextSeo } from 'next-seo'
import HScroll from 'src/components/molecules/HScroll'
import ProductCard01 from 'src/components/organisms/ProductCard01'
import HeaderTemplate from 'src/components/templates/HeaderTemplate'
import BannerCard from 'src/components/organisms/BannerCard'
import HoverExpand from 'src/components/organisms/HoverExpand'

export const getStaticProps: GetStaticProps = async () => ({
  props: { data: ['Karthick', 'Ragavendran'] }, // will be passed to the page component as props
})

const Home: NextPage = ({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log(data)

  return (
    <div>
      <NextSeo
        title='Next boilerplate.'
        description='A short description goes here which says what goes here.'
      />

      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='container mx-auto'>
        <VideoPlayer />
        <br className='my-12' />
        <BannerItems className='max-w-lg mx-auto mt-12 text-center text-black'>
          <BannerItems.Text variant='displayText'>
            OWN THE FLOOR: AC BONIFACIO
          </BannerItems.Text>
          <BannerItems.Text className='mt-3'>
            In the past, dance wasn’t recognised and AC Bonifacio decided to
            challenge that.
            <br />
            Using her star power to inspire her community to find their
            confidence, share their passions and put dance in the spotlight.
          </BannerItems.Text>
          <div className='flex justify-center gap-2 mt-6'>
            <BannerItems.Button variant='black' href='/'>
              Explore
            </BannerItems.Button>
            <BannerItems.Button variant='black' href='/'>
              Shop
            </BannerItems.Button>
          </div>
        </BannerItems>
        <HScroll className='mt-48'>
          <div className='flex py-2'>
            <h2 className='text-xl font-semibold'>New Arrivals</h2>
            <div className='flex gap-4 ml-auto'>
              <HScroll.RightArrow distance={-200}>
                <div className='flex items-center justify-center w-10 h-10 p-2 bg-gray-100 rounded-full'>
                  <ChevronLeftIcon />
                </div>
              </HScroll.RightArrow>
              <HScroll.LeftArrow distance={200}>
                <div className='flex items-center justify-center w-10 h-10 p-2 bg-gray-100 rounded-full'>
                  <ChevronRightIcon />
                </div>
              </HScroll.LeftArrow>
            </div>
          </div>
          <HScroll.Body className='gap-3 pb-24'>
            <ProductCard01
              imgUrl='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355637/nike/revolt-164_6wVEHfI-unsplash_rb5kjn.jpg'
              key='1'
              displayName='Air Jordan 1 Mid'
              price={9995}
              category='Shoes'
            />
            <ProductCard01
              key='2'
              imgUrl='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/usama-akram-kP6knT7tjn4-unsplash_wb6kpd.jpg'
              displayName='Nike SB Dunk Low Pro'
              price={7995}
              category='Skate Shoes'
            />
            <ProductCard01
              key='3'
              imgUrl='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355637/nike/joseph-barrientos-4qSb_FWhHKs-unsplash_haog82.jpg'
              displayName='Nike City Rep TR'
              price={4995}
              category="Men's Training Shoe"
            />
            <ProductCard01
              key='4'
              imgUrl='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355638/nike/andres-jasso-PqbL_mxmaUE-unsplash_k77bnl.jpg'
              displayName='Air Jordan 1 Max'
              price={9995}
              category='Shoes'
            />
            <ProductCard01
              key='4'
              imgUrl='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'
              displayName='Air Jordan 1 Max'
              price={9995}
              category='Shoes'
            />
            <div key='5'>Hello</div>
            <div key='6'>Hello2</div>
            <div key='7'>Hello23</div>
          </HScroll.Body>
        </HScroll>
        <HeaderTemplate heading='The Latest'>
          <div className='grid grid-cols-4 gap-3 h-96 '>
            <Image
              className='block col-span-1'
              src='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'
              alt='running'
            />
            <Image
              src='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'
              alt='running'
            />
            <Image
              src='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'
              alt='running'
            />
            <Image
              src='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'
              alt='running'
            />
          </div>
        </HeaderTemplate>
        <BannerItems className='max-w-lg mx-auto mt-12 text-center text-black'>
          <BannerItems.Text variant='description'>
            Nike Zoom Fly 4
          </BannerItems.Text>
          <BannerItems.Text variant='displayText'>
            RACE DAY. <br /> EVERY DAY.
          </BannerItems.Text>

          <BannerItems.Button
            variant='black'
            href='/'
            className='inline-block mt-6'
          >
            Shop
          </BannerItems.Button>
        </BannerItems>
        <HeaderTemplate heading='Featured'>
          <div className='grid grid-cols-2 gap-6'>
            <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'>
              <BannerItems.Text variant='title'>
                Air Force 1 For All.
              </BannerItems.Text>

              <BannerItems.Button
                variant='black'
                href='/'
                className='inline-block mt-6'
              >
                Shop
              </BannerItems.Button>
            </BannerCard>
            <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg'>
              <BannerItems.Text variant='title'>
                Jordan Holiday Collection
              </BannerItems.Text>

              <BannerItems.Button
                variant='black'
                href='/'
                className='inline-block mt-6'
              >
                Shop
              </BannerItems.Button>
            </BannerCard>
          </div>
        </HeaderTemplate>
        <HeaderTemplate heading="Don't Miss">
          <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_800,h_500,q_30/v1640360278/nike/ginny-rose-stewart-UxkcSzRWM2s-unsplash_hpa1wa.jpg'>
            <BannerItems.Text variant='displayText' color='white'>
              NIKE YOGA
              <br />
              COLLECTION
            </BannerItems.Text>
            <BannerItems.Text
              variant='description'
              color='white'
              className='mt-2'
            >
              The perfect pieces to flow in.
            </BannerItems.Text>

            <BannerItems.Button
              variant='white'
              href='/'
              className='inline-block mt-6'
            >
              Shop
            </BannerItems.Button>
          </BannerCard>
        </HeaderTemplate>
        <HeaderTemplate heading='Trending'>
          <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_500,h_500,q_30/v1640355636/nike/irene-kredenets-dwKiHoqqxk8-unsplash_m4508r.jpg' />
        </HeaderTemplate>
        <BannerItems className='max-w-lg mx-auto mt-12 text-center text-black'>
          <BannerItems.Text variant='description'>
            Nike Air Max Dawn
          </BannerItems.Text>
          <BannerItems.Text variant='displayText'>
            A THROWBACK THAT MOVES FORWARD
          </BannerItems.Text>
          <BannerItems.Text variant='description' className='mt-4'>
            With familiar lines and a refreshed silhouette, the Air Max Dawn
            takes inspiration from the past so that you can bring your style
            into the future.
          </BannerItems.Text>

          <BannerItems.Button
            variant='black'
            href='/'
            className='inline-block mt-6'
          >
            Shop
          </BannerItems.Button>
        </BannerItems>
        <HeaderTemplate heading='More Nike'>
          <div className='grid grid-cols-4 gap-3'>
            <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,g_north,h_600,q_53,x_0,y_980/v1640243339/nike/men_rqgpei.jpg'>
              <BannerItems.Button href='/'>Men&apos;s</BannerItems.Button>
            </BannerCard>
            <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_400,h_600,q_50/v1640243339/nike/women_awptwe.jpg'>
              <BannerItems.Button href='/'>Women&apos;s</BannerItems.Button>
            </BannerCard>
            <BannerCard imgSrc='https://res.cloudinary.com/thankyou/image/upload/c_fill,w_400,h_600,q_50/v1640362989/nike/jonathan-borba-ptCuvqe9Okg-unsplash_y6gquj.jpg'>
              <BannerItems.Button href='/'>Kid&apos;s</BannerItems.Button>
            </BannerCard>
          </div>
        </HeaderTemplate>
        <HoverExpand className='py-6 my-6' />
      </main>
      <Footer className='mt-6' />
    </div>
  )
}

export default Home
